# Generated by Django 4.1.3 on 2024-05-17 18:19

import application.glass_management.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeglassFrameColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('color', models.CharField(max_length=255, unique=True, verbose_name='镜架颜色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeglassFrameDataFromExcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='镜架SKU')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='镜架品牌')),
                ('model_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='镜架型号')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='镜架材质')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='镜架颜色')),
                ('shape', models.CharField(blank=True, max_length=255, null=True, verbose_name='镜架形状')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='库存')),
                ('lens_width', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='镜圈宽度')),
                ('bridge_width', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='鼻梁宽度')),
                ('temple_length', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='镜腿长度')),
            ],
        ),
        migrations.CreateModel(
            name='EyeglassFrameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='镜架SKU')),
                ('brand', models.CharField(max_length=255, verbose_name='镜架品牌')),
                ('model_type', models.CharField(max_length=255, verbose_name='镜架型号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='售价')),
                ('isnosepad', models.BooleanField(verbose_name='是否带鼻托')),
                ('lens_radian', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='撑片弧度')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='库存')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframecolortype', verbose_name='镜架颜色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeglassFrameMaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('material', models.CharField(max_length=255, unique=True, verbose_name='镜架材质')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeglassFrameShapeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('shape', models.CharField(max_length=255, unique=True, verbose_name='镜架形状')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeglassFrameStyleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('style', models.CharField(max_length=255, unique=True, verbose_name='风格')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeglassFrameEntryStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframeentry', verbose_name='镜架基本信息')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframestyletype', verbose_name='镜架风格')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframematerialtype', verbose_name='镜架材质'),
        ),
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframeshapetype', verbose_name='镜架形状'),
        ),
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='所属仓库'),
        ),
        migrations.CreateModel(
            name='EyeglassFrameDetectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('frontview', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='正视图')),
                ('sideview', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='侧视图')),
                ('topview', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='俯视图')),
                ('frontview_bg', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='正视图背景')),
                ('sideview_bg', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='侧视图背景')),
                ('topview_bg', models.ImageField(upload_to=application.glass_management.models.get_upload_eyeglass_path, verbose_name='俯视图背景')),
                ('frame_height', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜框高度')),
                ('frame_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜框宽度')),
                ('pile_height_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左桩头高度')),
                ('pile_height_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右桩头高度')),
                ('frame_top_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜框顶部宽度')),
                ('top_points', models.CharField(max_length=255, verbose_name='镜框左右最高点坐标（两组）')),
                ('frame_rects', models.CharField(max_length=255, verbose_name='镜框左右矩形坐标及宽高（两组）')),
                ('lens_width_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜圈宽度')),
                ('lens_width_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜圈宽度')),
                ('lens_height_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜圈高度')),
                ('lens_height_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜圈高度')),
                ('lens_diagonal_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜圈对角线长度')),
                ('lens_diagonal_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜圈对角线长度')),
                ('lens_area_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜圈面积')),
                ('lens_area_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜圈面积')),
                ('bridge_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='鼻梁宽度')),
                ('lens_center_points', models.CharField(max_length=255, verbose_name='镜圈中心点坐标（两组）')),
                ('lens_top_points', models.CharField(max_length=255, verbose_name='镜圈顶部点坐标（两组）')),
                ('vertical_angle', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='垂俯角')),
                ('forward_angle', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='前倾角')),
                ('temple_angle', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜腿角')),
                ('drop_length', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='垂长')),
                ('face_angle', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='面弯')),
                ('sagittal_angle_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左垂内角')),
                ('sagittal_angle_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右垂内角')),
                ('temple_length_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜腿长度')),
                ('temple_length_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜腿长度')),
                ('temporal_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='颞距')),
                ('spread_angle_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左镜腿外张角')),
                ('spread_angle_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右镜腿外张角')),
                ('pile_distance', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='桩头距离')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='重量')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_management.eyeglassframeentry', verbose_name='镜架基本信息')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
