# Generated by Django 4.1.3 on 2024-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='bridge_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='鼻梁宽度'),
        ),
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='lens_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='镜圈宽度'),
        ),
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='temple_length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='镜腿长度'),
        ),
        migrations.AlterField(
            model_name='eyeglassframedatafromexcel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
