# Generated by Django 4.1.3 on 2024-05-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('glass_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeglassframeentry',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='所属仓库'),
            preserve_default=False,
        ),
    ]
