# Generated by Django 4.1.3 on 2024-05-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glass_management', '0002_eyeglassframeentry_bridge_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyeglassframedatafromexcel',
            name='quantity',
        ),
    ]
