# Generated by Django 4.1.3 on 2024-05-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glass_management', '0003_rename_bridge_width_eyeglassframedatafromexcel_bridge_width_st_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyeglassframedatafromexcel',
            old_name='bridge_width',
            new_name='bridge_width_st',
        ),
        migrations.RenameField(
            model_name='eyeglassframedatafromexcel',
            old_name='lens_width',
            new_name='lens_width_st',
        ),
        migrations.RenameField(
            model_name='eyeglassframedatafromexcel',
            old_name='temple_length',
            new_name='temple_length_st',
        ),
        migrations.RenameField(
            model_name='eyeglassframeentry',
            old_name='bridge_width',
            new_name='bridge_width_st',
        ),
        migrations.RenameField(
            model_name='eyeglassframeentry',
            old_name='lens_width',
            new_name='lens_width_st',
        ),
        migrations.RenameField(
            model_name='eyeglassframeentry',
            old_name='temple_length',
            new_name='temple_length_st',
        ),
    ]
