# Generated by Django 4.1.3 on 2024-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glass_management', '0004_rename_bridge_width_eyeglassframedatafromexcel_bridge_width_st_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eyeglassframedatafromexcel',
            index=models.Index(fields=['sku'], name='glass_manag_sku_8772dd_idx'),
        ),
        migrations.AddIndex(
            model_name='eyeglassframedatafromexcel',
            index=models.Index(fields=['model_type'], name='glass_manag_model_t_9ee182_idx'),
        ),
    ]
