# Generated by Django 4.1.3 on 2024-10-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glass_management', '0005_eyeglassframedatafromexcel_glass_manag_sku_8772dd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyeglassframedetectionresult',
            name='frontview_bg',
        ),
        migrations.RemoveField(
            model_name='eyeglassframedetectionresult',
            name='sideview_bg',
        ),
        migrations.RemoveField(
            model_name='eyeglassframedetectionresult',
            name='topview_bg',
        ),
    ]
