# Generated by Django 4.1.3 on 2024-10-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "glass_management",
            "0005_eyeglassframedatafromexcel_glass_manag_sku_8772dd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eyeglassframeentry",
            name="is_transparent",
            field=models.IntegerField(
                choices=[(0, "否"), (1, "是")], default=0, verbose_name="是否透明"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eyeglassframeentry",
            name="bridge_width_st",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="鼻梁宽度"
            ),
        ),
        migrations.AlterField(
            model_name="eyeglassframeentry",
            name="lens_width_st",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="镜圈宽度"
            ),
        ),
        migrations.AlterField(
            model_name="eyeglassframeentry",
            name="temple_length_st",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="镜腿长度"
            ),
        ),
    ]
