# Generated by Django 4.1.3 on 2024-05-10 17:23

import application.glass_recommendation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeglassFrameRecommendationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('facial_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('nose_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('left_ear_distance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('right_ear_distance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('iris_center_distance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('left_eye_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('right_eye_width', models.DecimalField(decimal_places=4, max_digits=15)),
                ('left_eye_height', models.DecimalField(decimal_places=4, max_digits=15)),
                ('right_eye_height', models.DecimalField(decimal_places=4, max_digits=15)),
                ('inner_eyecorner_distance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('outter_eyecorner_distance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('face_type', models.CharField(blank=True, max_length=255)),
                ('skin_color', models.CharField(blank=True, max_length=255)),
                ('pupil_distance', models.DecimalField(blank=True, decimal_places=4, max_digits=15)),
                ('myopia_left', models.BigIntegerField(blank=True)),
                ('myopia_right', models.BigIntegerField(blank=True)),
                ('astigmatism_left', models.BigIntegerField(blank=True)),
                ('astigmatism_right', models.BigIntegerField(blank=True)),
                ('lens_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=15)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('age', models.SmallIntegerField(blank=True)),
                ('career', models.CharField(blank=True, max_length=255)),
                ('price_max', models.BigIntegerField(blank=True)),
                ('price_min', models.BigIntegerField(blank=True)),
                ('style_list', models.CharField(blank=True, max_length=255)),
                ('brand_list', models.CharField(blank=True, max_length=255)),
                ('material_list', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户识别码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUserOptometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('pupil_distance', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='瞳距')),
                ('myopia_hyperopia_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左眼屈光度')),
                ('myopia_hyperopia_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右眼屈光度')),
                ('astigmatism_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左眼散光度')),
                ('astigmatism_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右眼散光度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_recommendation.recommendationuser', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUserLens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('refractive_index', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜片折射率')),
                ('diameter', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜片直径')),
                ('density', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='镜片密度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_recommendation.recommendationuser', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUserFacialScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('outer_canthic_diameter', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='外眼角间距')),
                ('inner_canthic_diameter', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='内眼角间距')),
                ('eye_width_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左眼宽')),
                ('eye_width_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右眼宽')),
                ('eye_height_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左眼高')),
                ('eye_height_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右眼高')),
                ('ala_nasi_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='鼻翼宽')),
                ('nasion_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='鼻根宽')),
                ('nose_height', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='鼻高')),
                ('nose_pivot_angle', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='鼻基准角')),
                ('head_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='头宽')),
                ('side_face_length_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左侧面长')),
                ('side_face_length_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右侧面长')),
                ('outer_canthic_ear_left', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='左外眼角耳距')),
                ('outer_canthic_ear_right', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='右外眼角耳距')),
                ('eyebrow_center_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='眉上顶点距')),
                ('face_height', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='脸高')),
                ('lip_width', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='嘴唇宽')),
                ('lip_height', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='嘴唇高')),
                ('face_type', models.SmallIntegerField(choices=[(0, '菱形脸'), (1, '圆脸'), (2, '方脸'), (3, '长脸'), (4, '心形脸'), (5, '鹅蛋脸')], verbose_name='脸型：0-菱形脸 1-圆脸 2-方脸 3-长脸 4-心形脸 5-鹅蛋脸')),
                ('skin_color_type', models.SmallIntegerField(choices=[(0, '偏黑'), (1, '适中'), (2, '偏白')], verbose_name='肤色：0-偏黑 1-适中 2-偏白')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_recommendation.recommendationuser', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUserFacialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('frontview', models.ImageField(upload_to=application.glass_recommendation.models.get_upload_userface_path, verbose_name='用户人脸正视图')),
                ('leftview', models.ImageField(upload_to=application.glass_recommendation.models.get_upload_userface_path, verbose_name='用户人脸左视图')),
                ('rightview', models.ImageField(upload_to=application.glass_recommendation.models.get_upload_userface_path, verbose_name='用户人脸右视图')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_recommendation.recommendationuser', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationUserBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], help_text='性别：0-保密 1-男 2-女', verbose_name='性别：0-保密 1-男 2-女')),
                ('age_range', models.SmallIntegerField(choices=[(1, '14岁以下'), (2, '15-25岁'), (3, '26-35岁'), (4, '36-45岁'), (5, '46-60岁'), (6, '61岁以上')], help_text='年龄段：0-保密 1-14岁以下 2-15-25岁 3-26-35岁 4-36-45岁 5-46-60岁 6-61岁以上', verbose_name='年龄段：0-保密 1-14岁以下 2-15-25岁 3-26-35岁 4-36-45岁 5-46-60岁 6-61岁以上')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glass_recommendation.recommendationuser', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
