# Generated by Django 4.1.3 on 2025-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键ID",
                    ),
                ),
                ("create_user", models.IntegerField(default=0, verbose_name="创建人")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        max_length=11,
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                ("update_user", models.IntegerField(default=0, verbose_name="更新人")),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, max_length=11, null=True, verbose_name="更新时间"
                    ),
                ),
                ("is_delete", models.BooleanField(default=0, verbose_name="逻辑删除")),
                (
                    "warehouse",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="仓库名称"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="仓库地址")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
